/**
 * @file printTable.c
 * @brief c-code to print the polynomial table for ndlcoms crc16
 * @author Martin Zenzes
 * @date 2013-12-18
 */
#include <stdio.h>

/**
 * small piece of c-code to print the actual crc-table used for the crc16
 * algorithm as proposed by the RFC1662.
 *
 * see also
 *     https://tools.ietf.org/html/rfc1662.html
 */

void printTableHeader(const char* name, unsigned short poly)
{
       printf("/** crc table. generated by %s using the polynom 0x%04x */\n", name, poly);
       printf("static unsigned short crc_tab[256] = {");
}

/** taken from the RFC 1662
 * https://tools.ietf.org/html/rfc1662.html#ref-7
 */
void printTable1(unsigned short poly)
{
    int i, v, b;
    for (b = 0; ; )
    {
        if (b % 8 == 0)
            printf("\n    ");

        v = b;
        for (i = 8; i--; )
            v = v & 1 ? (v >> 1) ^ poly : v >> 1;

        printf("0x%04x", v & 0xFFFF);
        if (++b == 256)
            break;
        printf(", ");
    }
}
void printTableFooter()
{
       printf("\n};\n");
}

/**
 * this was copied from http://www.lammertbies.nl/download/lib_crc.zip
 * slightly modified for pretty-table-printing
 */
void printTable2( unsigned short poly )
{

    int i, j;
    unsigned short crc, c;

    for (i=0; i<256; i++)
    {
        if (!(i%8))
            printf("\n    ");

        crc = 0;
        c   = ((unsigned short) i) << 8;

        for (j=0; j<8; j++) {

            if ( (crc ^ c) & 0x8000 ) crc = ( crc << 1 ) ^ poly;
            else                      crc =   crc << 1;

            c = c << 1;
        }

        printf("0x%04x",crc);
        if (i != 255)
            printf(", ");
    }
}

int main(int argc, char *argv[])
{
    if (1)
    {
        /* funnily, the polynom given by the text of the RFC is 0x8408. but
         * when the resulting table is used, the "reveng" software say the
         * polynom used was 0x1021...
         */
        printTableHeader(argv[0], 0x8408);
        printTable1(0x8408);
        printTableFooter();
    } else {
        /* the second version uses a different source, and can be used as well.
         * is able to generate the famous "0xe5cc" test-crc
         */
        printTableHeader(argv[0], 0x1021);
        printTable2(0x1021);
        printTableFooter();
    }

    return 0;
}
