<?xml version="1.0"?>

<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text" encoding="ascii" />
<xsl:strip-space elements="/" />

<xsl:template match="/"># autogenerated file, do not modify...

use strict;
use warnings;
use Exporter;

# to use, use "use NDLComDeviceIds;"

our @ISA = qw( Exporter );

# only these are exported by default.
our @EXPORT = qw( NDLComDeviceNameToId NDLComDeviceIdToName );

# hash generated based on defined xml
my %names = (
<xsl:apply-templates select="//device" mode="perl-style"/>
);

# a second one, for the other way around
my %ids = reverse %names;

sub NDLComDeviceIdToName {
    return $ids{$_[0]};
}

sub NDLComDeviceNameToId {
    return $names{$_[0]};
}

1;
</xsl:template>

<!-- device elements -->
<xsl:template match="device" mode="perl-style" >
<!-- combine each "device" node to a enum entry -->
<xsl:text>    </xsl:text><xsl:value-of select="@name"/><xsl:text> => </xsl:text><xsl:value-of select="@id"/>
<!-- only print a comma if we are not the last item -->
<xsl:if test="(following-sibling::device)">,</xsl:if>
<!-- only print a comment after the enum if someone actually wrote one -->
<xsl:if test="text() != ''"><xsl:text> # </xsl:text><xsl:value-of select="text()"/></xsl:if>
<!-- and finally a newline, if we are not the last item -->
<xsl:if test="(following-sibling::device)"><xsl:text>
</xsl:text></xsl:if>
</xsl:template>

</xsl:stylesheet>
