<?xml version="1.0"?>

<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text" encoding="ascii" />
<xsl:strip-space elements="/" />

<xsl:template match="/"># autogenerated file, do not modify...

module NDLComDeviceIds

    NamesToIds = Hash[
<xsl:apply-templates select="//device" mode="yml-style-forward"/>
        ]

    IdsToNames = Hash[
<xsl:apply-templates select="//device" mode="yml-style-backward"/>
        ]

    def self.getName(id)
        raise ArgumentError, "NDLComDeviceIds::getName: argument is not numeric" unless id.is_a? Numeric

        retval = NDLComDeviceIds::IdsToNames["#{id}"]

        # we exit gracefull, as in the c-version
        #raise RangeError, "NDLComDeviceIds::getName: given id #{id} not found" if retval == nil

        return retval
    end

    def self.getId(name)
        raise ArgumentError, "NDLComDeviceIds::getId: argument is not string" unless name.is_a? String

        retval = NDLComDeviceIds::NamesToIds[name]

        # we exit gracefull, as in the c-version
        #raise RangeError, "NDLComDeviceIds::getId: given name #{name} not found" if retval == nil

        return retval
    end
end

</xsl:template>

<!-- device elements -->
<xsl:template match="device" mode="yml-style-forward" >
<!-- combine each "device" node to a enum entry -->
<xsl:text>            "</xsl:text><xsl:value-of select="@name"/><xsl:text>" => </xsl:text><xsl:value-of select="@id"/>
<!-- only print a comma if we are not the last item -->
<xsl:if test="(following-sibling::device)">,</xsl:if>
<!-- only print a comment after the enum if someone actually wrote one -->
<xsl:if test="text() != ''"><xsl:text> # </xsl:text><xsl:value-of select="text()"/></xsl:if>
<!-- and finally a newline, if we are not the last item -->
<xsl:if test="(following-sibling::device)"><xsl:text>
</xsl:text></xsl:if>
</xsl:template>

<xsl:template match="device" mode="yml-style-backward" >
<!-- combine each "device" node to a enum entry -->
<xsl:text>            "</xsl:text><xsl:value-of select="@id"/><xsl:text>" => '</xsl:text><xsl:value-of select="@name"/><xsl:text>'</xsl:text>
<!-- only print a comma if we are not the last item -->
<xsl:if test="(following-sibling::device)">,</xsl:if>
<!-- only print a comment after the enum if someone actually wrote one -->
<xsl:if test="text() != ''"><xsl:text> # </xsl:text><xsl:value-of select="text()"/></xsl:if>
<!-- and finally a newline, if we are not the last item -->
<xsl:if test="(following-sibling::device)"><xsl:text>
</xsl:text></xsl:if>
</xsl:template>

</xsl:stylesheet>
