#ifndef TESTGUI_H
#define TESTGUI_H

#include <QMainWindow>
#include <QMap>

/**
 * \internal
 * \namespace Ui
 * \brief Generated by Qt framework.
 */
namespace Ui
{
    class testGUI;
};
/* \endinternal */

class testGUI : public QMainWindow
{
    Q_OBJECT

    public:
        testGUI (QWidget *parent = 0);
        ~testGUI();

    private:
        Ui::testGUI* mpUi;
};

#endif //TESTGUI_H
