<?xml version="1.0"?>

<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text" encoding="ascii" />
<xsl:strip-space elements="/" />

<xsl:template match="/">/* autogenerated file, do not modify... */

#include "NDLCom/DeviceIds.h"
#include &lt;string.h&gt; // for strcmp

struct ndlcomDeviceEntrys
{
    ndlcomDeviceIdEnum id;
    const char* name;
};

static const struct ndlcomDeviceEntrys entrys[] =
{
<xsl:apply-templates select="//device"/>
    {0,0} // end-of-list
};

const char* ndlcomDeviceGetName(ndlcomId id)
{
    const struct ndlcomDeviceEntrys* entry = entrys;
    while(entry->name)
    {
        if (entry->id == id)
            return entry->name;
        ++entry;
    }
    return 0;
}

ndlcomId ndlcomDeviceGetId(const char* name)
{
    const struct ndlcomDeviceEntrys* entry = entrys;
    while(entry->name)
    {
        if (strcmp(name, entry->name) == 0)
            return entry->id;
        ++entry;
    }
    return 0;
}
</xsl:template>

<!-- device elements -->
<xsl:template match="device">
<!-- combine each "device" node to a enum entry -->
<xsl:text>    {</xsl:text><xsl:value-of select="@id"/>
<xsl:text>, "</xsl:text><xsl:value-of select="@name"/><xsl:text>"},</xsl:text>
<!-- only print a comment after the enum if someone actually wrote one -->
<xsl:if test="text() != ''"><xsl:text> // </xsl:text><xsl:value-of select="text()"/></xsl:if>
<!-- and finally a newline if we are not the last item -->
<xsl:if test="(following-sibling::device)"><xsl:text>
</xsl:text></xsl:if>
</xsl:template>

</xsl:stylesheet>
