<?xml version="1.0"?>

<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text" encoding="ascii" />
<xsl:strip-space elements="/" />

<xsl:template match="/">#ifndef NDLCOM_DEVICE_IDS_H_
#define NDLCOM_DEVICE_IDS_H_

/* autogenerated file, do not modify... */

#include "NDLCom/Types.h"

#if defined (__cplusplus)
extern "C" {
#endif

typedef enum
{
<xsl:apply-templates select="//device" mode="c-style"/>
} ndlcomDeviceIdEnum;

const char* ndlcomDeviceGetName(ndlcomId id);
ndlcomId ndlcomDeviceGetId(const char* name);

#if defined (__cplusplus)
}/*extern C*/
#endif

#if defined (__cplusplus)
namespace ndlcom
{
    namespace deviceId
    {
        enum id
        {
<xsl:apply-templates select="//device" mode="cxx-style"/>
        };

        inline const char* getName(ndlcomId id)
        {
            return ndlcomDeviceGetName(id);
        }
        inline ndlcomId getId(const char* name)
        {
            return ndlcomDeviceGetId(name);
        }
    };
};
#endif/*__cplusplus*/

#endif/*REPRESENTATIONS_XML_C_DEFINES_H_*/
</xsl:template>

<!-- device elements -->
<xsl:template match="device" mode="c-style" >
<!-- combine each "device" node to a enum entry -->
<xsl:text>    ndlcomDeviceId_</xsl:text><xsl:value-of select="@name"/><xsl:text> = </xsl:text><xsl:value-of select="@id"/>
<!-- only print a comma if we are not the last item -->
<xsl:if test="(following-sibling::device)">,</xsl:if>
<!-- only print a comment after the enum if someone actually wrote one -->
<xsl:if test="text() != ''"><xsl:text> ///&lt; </xsl:text><xsl:value-of select="text()"/></xsl:if>
<!-- and finally a newline, if we are not the last item -->
<xsl:if test="(following-sibling::device)"><xsl:text>
</xsl:text></xsl:if>
</xsl:template>

<!-- device elements -->
<xsl:template match="device" mode="cxx-style" >
<!-- combine each "device" node to a enum entry -->
<xsl:text>            </xsl:text><xsl:value-of select="@name"/><xsl:text> = </xsl:text><xsl:value-of select="@id"/>
<!-- only print a comma if we are not the last item -->
<xsl:if test="(following-sibling::device)">,</xsl:if>
<!-- only print a comment after the enum if someone actually wrote one -->
<xsl:if test="text() != ''"><xsl:text> ///&lt; </xsl:text><xsl:value-of select="text()"/></xsl:if>
<!-- and finally a newline, if we are not the last item -->
<xsl:if test="(following-sibling::device)"><xsl:text>
</xsl:text></xsl:if>
</xsl:template>

</xsl:stylesheet>
