<?xml version="1.0"?>

<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text" encoding="ascii" />
<xsl:strip-space elements="/" />

<xsl:template match="/"># autogenerated file, do not modify...

# hash generated based on defined xml
NDLComNameToDeviceId:
<xsl:apply-templates select="//device" mode="yml-style-forward"/>

# the other way around
NDLComDeviceIdToName:
<xsl:apply-templates select="//device" mode="yml-style-backward"/>

</xsl:template>

<!-- device elements -->
<xsl:template match="device" mode="yml-style-forward" >
<!-- combine each "device" node to a enum entry -->
<xsl:text>    </xsl:text><xsl:value-of select="@name"/><xsl:text> : </xsl:text><xsl:value-of select="@id"/>
<!-- only print a comment after the enum if someone actually wrote one -->
<xsl:if test="text() != ''"><xsl:text> # </xsl:text><xsl:value-of select="text()"/></xsl:if>
<!-- and finally a newline, if we are not the last item -->
<xsl:if test="(following-sibling::device)"><xsl:text>
</xsl:text></xsl:if>
</xsl:template>

<xsl:template match="device" mode="yml-style-backward" >
<!-- combine each "device" node to a enum entry -->
<xsl:text>    </xsl:text><xsl:value-of select="@id"/><xsl:text> : '</xsl:text><xsl:value-of select="@name"/><xsl:text>'</xsl:text>
<!-- only print a comment after the enum if someone actually wrote one -->
<xsl:if test="text() != ''"><xsl:text> # </xsl:text><xsl:value-of select="text()"/></xsl:if>
<!-- and finally a newline, if we are not the last item -->
<xsl:if test="(following-sibling::device)"><xsl:text>
</xsl:text></xsl:if>
</xsl:template>

</xsl:stylesheet>
