/**
 * @file src/representation_mapper.cpp
 * @author zenzes
 * @date 2011
 */

#include <QDebug>
#include <QMetaType>
#include "NDLCom/representation_mapper.h"
#include "NDLCom/message.h"

#include "ui_show_representations.h"

#include <math.h>

/* extra types of representation */
#include "representations/representation.h"
#include "representations/names.h"
#include "representations/id.h"
/* please keep this list alphabetically sorted */
#include "representations/acceleration.h"
#include "representations/current_values.h"
#include "representations/debug_message.h"
#include "representations/distance_si1120.h"
#include "representations/dms_board_config.h"
#include "representations/dms_raw.h"
#include "representations/force_torque.h"
#include "representations/joint_angles.h"
#include "representations/memory.h"
#include "representations/ping.h"
#include "representations/register.h"
#include "representations/sensor_array.h"
#include "representations/telemetry_values.h"
#include "representations/bldc_joint_telemetry.h"
#include "representations/temperature.h"
#include "representations/thermometer_ds18b20.h"

NDLCom::RepresentationMapper::RepresentationMapper(QWidget* parent) : QWidget(parent)
{
    /* should be moved into main gui? */
    qRegisterMetaType<ProtocolHeader>("ProtocolHeader");

    /* please keep this list alphabetically sorted */
    qRegisterMetaType<Representations::Acceleration>("Representations::Acceleration");
    qRegisterMetaType<Representations::DMSBoardConfig>("Representations::DMSBoardConfig");
    qRegisterMetaType<Representations::DebugMessage>("Representations::DebugMessage");
    qRegisterMetaType<Representations::DistanceSI1120>("Representations::DistanceSI1120");
    qRegisterMetaType<Representations::DmsRaw>("Representations::DmsRaw");
    qRegisterMetaType<Representations::ForceTorque>("Representations::ForceTorque");
    qRegisterMetaType<Representations::JointAngles>("Representations::JointAngles");
    qRegisterMetaType<Representations::MemoryData>("Representations::MemoryData");
    qRegisterMetaType<Representations::Ping>("Representations::Ping");
    qRegisterMetaType<Representations::RegisterDescriptionResponse>("Representations::RegisterDescriptionResponse>");
    qRegisterMetaType<Representations::RegisterValueResponse>("RegisterValueResponse");
    qRegisterMetaType<Representations::SensorArray_channelData>("Representations::mIdSensorArray_channelData");
    qRegisterMetaType<Representations::SensorArray_matrixData>("Representations::mIdSensorArray_matrixData");
    qRegisterMetaType<Representations::SensorArray_vectorData>("Representations::mIdSensorArray_vectorData");
    qRegisterMetaType<Representations::TelemetryValues>("Representations::TelemetryValues");
    qRegisterMetaType<Representations::BLDCJointTelemetryMessage>("Representations::BLDCJointTelemetryMessage");
    qRegisterMetaType<Representations::Temperature>("Representations::Temperature");
    qRegisterMetaType<Representations::ThermometerDS18B20>("Representations::ThermometerDS18B20");
    qRegisterMetaType<NDLCom::Message>("NDLCom::Message");

    /* this is the Message-signal emitted by the derived class NDLCom. we connect it to here, so we
     * can map the incoming message to all type which are there */
    connect(this, SIGNAL(rxMessage(const ::NDLCom::Message&)), this, SLOT(slot_rxMessage(const ::NDLCom::Message&)));
    /* these are internal Messages generated by the Composer for example, which should be sent to
     * the Gui aswell. for testing purposes for example */
    connect(this, SIGNAL(internal_txMessage(const ::NDLCom::Message&)), this, SLOT(slot_rxMessage(const ::NDLCom::Message&)));

    /* used to delimit number in the exportString */
    exportDelimiter = ",";

    /* used by printf to print into */
    pBuffer = new char[4096];
}
NDLCom::RepresentationMapper::~RepresentationMapper()
{
    delete[] pBuffer;
}

/* time, senderId, receiverId, paketCounter */
QString NDLCom::RepresentationMapper::printMessageHeader(const ::NDLCom::Message& msg)
{
    sprintf(pBuffer,"%ld.%09ld", msg.mTimestamp.tv_sec, msg.mTimestamp.tv_nsec);
    QString time = QString(pBuffer);
    sprintf(pBuffer,"%s %i%s %i%s %i",exportDelimiter,msg.mHdr.mSenderId,
                                     exportDelimiter,msg.mHdr.mReceiverId,
                                     exportDelimiter,msg.mHdr.mCounter);
    QString header = QString(pBuffer);
    return time + header;
}

void NDLCom::RepresentationMapper::slot_rxMessage(const ::NDLCom::Message& msg)
{
    /* than, we try to get a pointer to representation-data */
    const Representations::Representation* repreData = reinterpret_cast<const Representations::Representation*>(msg.mpDecodedData);

    try
    {
        bool hasFixedSize =
            (   repreData->mId == REPRESENTATIONS_REPRESENTATION_ID_DebugMessage
             || repreData->mId == REPRESENTATIONS_REPRESENTATION_ID_RegisterDescriptionResponse
            ) ? false : true;

        //handle packets with dynamic size
        //DebugMessage has a dynamic size and needs special treatment
        if (!hasFixedSize)
        {
            if(msg.mHdr.mDataLen < Representations::getSize(repreData->mId))
            {
                qWarning() << "Parser: packet too small.";
            }
            if(repreData->mId == REPRESENTATIONS_REPRESENTATION_ID_DebugMessage)
            {
                const Representations::DebugMessage* msgHdr = reinterpret_cast<const Representations::DebugMessage*>(repreData);
                int structLength = sizeof(Representations::DebugMessage);
                QString messageText = QString::fromAscii((const char*)(msgHdr + structLength), msg.mHdr.mDataLen - structLength);
                const char* senderName = Representations::Names::getDeviceName(msg.mHdr.mSenderId);
                qDebug("%s (id=%d): %s", senderName, msg.mHdr.mSenderId, messageText.toAscii().data());
            }
            else if(repreData->mId == REPRESENTATIONS_REPRESENTATION_ID_RegisterDescriptionResponse)
            {
                //dynamic length: the description data follows the RegisterValueResponse struct.
                int structLength = sizeof(Representations::RegisterDescriptionResponse);
                int descrLength = msg.mHdr.mDataLen - structLength;
                const Representations::RegisterDescriptionResponse r = *(Representations::RegisterDescriptionResponse*)repreData;
                const QByteArray description((char*)repreData + structLength, descrLength);
                emit rxRepresentation(msg.mHdr,r,description);
            }
        }
        else
        {
            /* check size */
            const ssize_t expectedSize = Representations::getSize(repreData->mId);
            if (expectedSize != msg.mHdr.mDataLen)
            {
                throw size_t(expectedSize);
            }
            /* prepare this as the "header" of the msg, which is sent through exportString */
            QString messageString = printMessageHeader(msg);
            /* and switch to the correct signal */
            /* please keep this list alphabetically sorted */
            switch(repreData->mId)
            {
                case REPRESENTATIONS_REPRESENTATION_ID_Acceleration:
                    sprintf(pBuffer,"%s %f%s %f%s %f\n",exportDelimiter, ((Representations::Acceleration*)repreData)->accX,
                                                        exportDelimiter, ((Representations::Acceleration*)repreData)->accY,
                                                        exportDelimiter, ((Representations::Acceleration*)repreData)->accZ);
                    emit exportString(QString(representationsNamesGetRepresentationName(repreData->mId)), messageString+QString(pBuffer));
                    emit rxRepresentation(msg.mHdr, *(Representations::Acceleration*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_CurrentValues:
                    emit rxRepresentation(msg.mHdr, *(Representations::CurrentValues*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_DMSBoardConfig:
                    emit rxRepresentation(msg.mHdr, *(Representations::DMSBoardConfig*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_DistanceSI1120:
                    sprintf(pBuffer,"%s %i\n",exportDelimiter, ((Representations::DistanceSI1120*)repreData)->distance_mm);
                    emit exportString(QString(representationsNamesGetRepresentationName(repreData->mId)), messageString+QString(pBuffer));
                    emit rxRepresentation(msg.mHdr, *(Representations::DistanceSI1120*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_DmsRaw:
                    emit rxRepresentation(msg.mHdr, *(Representations::DmsRaw*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_ForceTorque:
                    emit rxRepresentation(msg.mHdr, *(Representations::ForceTorque*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_JointAngles:
                    sprintf(pBuffer,"%s %f%s %f%s %f\n", exportDelimiter, ((Representations::JointAngles*)repreData)->rotX/32768*M_PI,
                                                        exportDelimiter, ((Representations::JointAngles*)repreData)->rotY/32768*M_PI,
                                                        exportDelimiter, ((Representations::JointAngles*)repreData)->rotZ/32768*M_PI);
                    emit exportString(QString(representationsNamesGetRepresentationName(repreData->mId)), messageString+QString(pBuffer));
                    emit rxRepresentation(msg.mHdr, *(Representations::JointAngles*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_MemoryData:
                    emit rxRepresentation(msg.mHdr, *(Representations::MemoryData*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_RepresentationsPing:
                    sprintf(pBuffer,"%s %i%s %lu%s %i\n",exportDelimiter, ((Representations::Ping*)repreData)->mType,
                                                         exportDelimiter, (long unsigned int)((Representations::Ping*)repreData)->mCurrentTimeCounter,
                                                         exportDelimiter, ((Representations::Ping*)repreData)->mPaketId);
                    emit exportString(QString(representationsNamesGetRepresentationName(repreData->mId)), messageString+QString(pBuffer));
                    emit rxRepresentation(msg.mHdr, *(Representations::Ping*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_RegisterValueResponse:
                    emit rxRepresentation(msg.mHdr, *(Representations::RegisterValueResponse*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_SensorArray_channelData:
                    emit rxRepresentation(msg.mHdr, *(Representations::SensorArray_channelData*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_SensorArray_matrixData:
                    emit rxRepresentation(msg.mHdr, *(Representations::SensorArray_matrixData*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_SensorArray_vectorData:
                    emit rxRepresentation(msg.mHdr, *(Representations::SensorArray_vectorData*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_TelemetryValues:
                    sprintf(pBuffer,"%s %i%s %i%s %i%s %i%s %i\n",exportDelimiter, ((Representations::TelemetryValues*)repreData)->value[4]*4,
                                                        exportDelimiter, ((Representations::TelemetryValues*)repreData)->value[14]*4,
                                                        exportDelimiter, ((Representations::TelemetryValues*)repreData)->value[1],
                                                        exportDelimiter, ((Representations::TelemetryValues*)repreData)->value[13],
                                                        exportDelimiter, ((Representations::TelemetryValues*)repreData)->value[7]);
                    emit exportString(QString(representationsNamesGetRepresentationName(repreData->mId)), messageString+QString(pBuffer));
                    emit rxRepresentation(msg.mHdr, *(Representations::TelemetryValues*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_BLDCJointTelemetryMessage:
                    // FIXME: versteht ich nicht - hab da kein Bock drauf - mir viel yu konpliziert - machs doch selbst (ts)
                    // sprintf(pBuffer,"%s %i%s %i%s %i%s %i%s %i\n",exportDelimiter, ((Representations::TelemetryValues*)repreData)->value[4]*4,
                    //                                     exportDelimiter, ((Representations::TelemetryValues*)repreData)->value[14]*4,
                    //                                     exportDelimiter, ((Representations::TelemetryValues*)repreData)->value[1],
                    //                                     exportDelimiter, ((Representations::TelemetryValues*)repreData)->value[13],
                    //                                     exportDelimiter, ((Representations::TelemetryValues*)repreData)->value[7]);
                    // emit exportString(QString(representationsNamesGetRepresentationName(repreData->mId)), messageString+QString(pBuffer));
                    emit rxRepresentation(msg.mHdr, *(Representations::BLDCJointTelemetryMessage*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_Temperature:
                    sprintf(pBuffer,"%s %hhu%s %hu\n", exportDelimiter, ((Representations::Temperature*)repreData)->thermometerId,
                                                      exportDelimiter, ((Representations::Temperature*)repreData)->centiCelsius);
                    emit exportString(QString(representationsNamesGetRepresentationName(repreData->mId)), messageString+QString(pBuffer));
                    emit rxRepresentation(msg.mHdr, *(Representations::Temperature*)repreData);
                    break;
                case REPRESENTATIONS_REPRESENTATION_ID_ThermometerDS18B20:
                    emit rxRepresentation(msg.mHdr, *(Representations::ThermometerDS18B20*)repreData);
                    break;
            }
        }
    }
    catch(size_t wrongLength)
    {
        qWarning() << tr("RepresentationMapper: [%1->%2] Representation::%3 with wrong length: Got %4, expected %5.")
            .arg(Representations::Names::getDeviceName(msg.mHdr.mSenderId))
            .arg(Representations::Names::getDeviceName(msg.mHdr.mReceiverId))
            .arg(Representations::Names::getRepresentationName(msg.mpDecodedData[0]))
            .arg(msg.mHdr.mDataLen)
            .arg(wrongLength);
    }
}

/* constructor of little widget to show all Representation-names and Device-name with their Id ! */
NDLCom::ShowRepresentations::ShowRepresentations(QWidget* parent) : QWidget(parent)
{
    Ui::ShowRepresentations* ui = new Ui::ShowRepresentations();
    ui->setupUi(this);

    int rowCounter = 0;
    for (int id = 0;id<=255;id++)
    {
        if (representationsNamesGetDeviceName(id))
        {
            rowCounter++;
            QString number = QString("0x%1").arg(id,2,16,QChar('0'));
            QString name(representationsNamesGetDeviceName(id));
            ui->deviceGrid->addWidget(new QLabel(number,this), rowCounter, 0);
            ui->deviceGrid->addWidget(new QLabel(name,this), rowCounter, 1);
        }
    }

    rowCounter = 0;
    for (int id = 0;id<=255;id++)
    {
        if (representationsNamesGetRepresentationName(id))
        {
            rowCounter++;
            QString number = QString("0x%1").arg(id,2,16,QChar('0'));
            QString size = QString::number(Representations::getSize(id));
            QString name(representationsNamesGetRepresentationName(id));
            ui->repreGrid->addWidget(new QLabel(number,this), rowCounter, 0);
            ui->repreGrid->addWidget(new QLabel(size,this), rowCounter, 1);
            ui->repreGrid->addWidget(new QLabel(name,this), rowCounter, 2);
        }
    }
}

